[package]
name = "fugue-static"
version = "0.1.2"
authors = ["Sam Thomas <st@xv.ax>"]
edition = "2018"

[dependencies]
fugue = { version = "0.1", registry = "fugue" }
petgraph = "0.6"
thiserror = "1"
